on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: staging
            prod: false
          - environment: production
            prod: true    
    environment:
      name: ${{ matrix.environment }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5

      - uses: denoland/setup-deno@v2
        with:
          cache: true

      - run: deno install

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - run: npm run build
        env:
          SANITY_STUDIO_ID: ${{ vars.SANITY_STUDIO_ID }}
          SANITY_STUDIO_DATASET: ${{ vars.SANITY_STUDIO_DATASET }}

      - run: |
          deno deploy \
            --org=${{ vars.DENO_DEPLOY_ORG }} \
            --app=${{ vars.DENO_DEPLOY_APP }} \
            --token=${{ secrets.DENO_DEPLOY_TOKEN }} \
            ${{ matrix.prod && '--prod' || '' }} \
            dist

      - run: npx sanity graphql deploy --force
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
          SANITY_STUDIO_ID: ${{ vars.SANITY_STUDIO_ID }}
          SANITY_STUDIO_DATASET: ${{ vars.SANITY_STUDIO_DATASET }}
